apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  config.yaml: |
    ---
    apiVersion: accounting.fits.extensions.config.gardener.cloud/v1alpha1
    kind: ControllerConfiguration
{{- if .Values.config.clientConnection }}
    clientConnection:
      acceptContentTypes: {{ required ".Values.config.clientConnection.acceptContentTypes is required" .Values.config.clientConnection.acceptContentTypes }}
      contentType: {{ required ".Values.config.clientConnection.contentType is required" .Values.config.clientConnection.contentType }}
      qps: {{ required ".Values.config.clientConnection.qps is required" .Values.config.clientConnection.qps }}
      burst: {{ required ".Values.config.clientConnection.burst is required" .Values.config.clientConnection.burst }}
{{- end }}

    accounting:
      metalURL: {{ .Values.config.accounting.metalURL }}
      metalHMAC: {{ .Values.config.accounting.metalHMAC }}
      metalAuthType: {{ .Values.config.accounting.metalAuthType }}

      ca: {{ .Values.config.accounting.apiCA }}
      cert: {{ .Values.config.accounting.apiCert }}
      key: {{ .Values.config.accounting.apiKey }}

{{- if .Values.config.imagePullSecret.encodedDockerConfigJSON }}
    imagePullSecret:
      encodedDockerConfigJSON: {{ .Values.config.imagePullSecret.encodedDockerConfigJSON }}
{{- end }}
