//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2024 Copyright FI-TS Finanz Informatik Technologie Service.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package accounting

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountingConfig) DeepCopyInto(out *AccountingConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountingConfig.
func (in *AccountingConfig) DeepCopy() *AccountingConfig {
	if in == nil {
		return nil
	}
	out := new(AccountingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccountingConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
